### PR TITLE
add curriculum graphs

### PR DESCRIPTION
**Pull request by rzig**
Pretty big PR, sorry. Big things are:
- Adds (autogenerated) curriculum graph javascript files to the `docs/static` folder. These are imported on curriculum graph pages
  - Used an mkdocs hook to serve these files, you shouldn't need to touch this
- Added curriculum graph pages with some minimal custom HTML. You shouldn't need to worry about editing the HTML
- Graphs are large, so I chose to hide them on mobile devices
- I made a [new repo](https://github.com/hkn-alpha/coursegraph) with all the code to read course explorer data and generate the code for these graphs

### CODE REVIEW

**Review by lnguy7 — APPROVED** [review]
This looks sick asf but is it possible to change the background of the graph part

**Comment by rzig** [comment]
image

**Comment by rzig** [comment]
Added a dot grid

**Comment by lnguy7** [comment]
Looks perf will merge

**Pull request merged**
