### PR TITLE
HKN Wiki Structure Complete

### PR DESCRIPTION
**Pull request by alex-m-zhang**
Set up the entire structure, leaving content for later.

### CODE REVIEW

**Comment by alex-m-zhang** [comment]
A concern: Under course wiki->ECE Course Offerings (for example), there will be a lot of courses, so the navigation bar is going to be very long. Is this ok? Or should we have a better way or organizing this?

**Comment by lnguy7** [comment]
Is it possible for the tabs on the top bar to have a dropdown

**Comment by alex-m-zhang** [comment]
Add fundamentals in engineering study materials to more advice or wherever the other stuff is.

**Comment by rzig** [comment]
Not possible unfortunately
https://github.com/squidfunk/mkdocs-material/discussions/2198?sort=top#discussioncomment-272434

**Comment by rzig** [comment]
LGTM

**Review by rzig — APPROVED** [review]

**Review by lnguy7 — APPROVED** [review]
LGTM2

**Pull request merged**
